Topluluk_Duyuru/Controllers/AdminController.cs
using MongoDB.Driver;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Topluluk_Duyuru.Models;

namespace Topluluk_Duyuru.Controllers
{
    public class AdminController : Controller
    {

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Admin admin)
        {
            Models.MongoHelper.ConnectToMongoService();
            Models.MongoHelper.admin_collection = Models.MongoHelper.database.GetCollection<Models.Admin>("admin");
            var user = Builders<Models.Admin>.Filter.Eq("username", admin.username);
            var pass = Builders<Models.Admin>.Filter.Eq("password", admin.password);

            if (user != null && pass != null)
            {
                FormsAuthentication.SetAuthCookie(admin.username, false);
                return RedirectToAction("Create", "Duyuru");
            }
            else
            {
                ViewBag.Mesaj = "Geçersiz Kullanıcı Adı veya Şifre";
                return View();
            }

        }
    }
}

Topluluk_Duyuru/Controllers/DuyuruListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MongoDB.Driver;

namespace Topluluk_Duyuru.Controllers
{
    public class DuyuruListController:Controller
    {
        public ActionResult List()
        {
            Models.MongoHelper.ConnectToMongoService();
            Models.MongoHelper.duyurular_collection =
                Models.MongoHelper.database.GetCollection<Models.Duyuru>("duyurular");
            var filter = Builders<Models.Duyuru>.Filter.Ne("_id", "");
            var result = Models.MongoHelper.duyurular_collection.Find(filter).ToList();

            return View(result);
        }
    }
}

Topluluk_Duyuru/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - İnönü Üniversitesi</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Üniversite Topluluğu Duyuru", "List", "DuyuruList", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Giriş Sayfası", "Login", "Admin")</li>
                    <li>@Html.ActionLink("Hakkımızda", "About", "Home")</li>
                    <li>@Html.ActionLink("İletişim", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - İnönü Üniversitesi</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>